version: '3.8'
services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: " -jar DynamoDBLocal.jar -sharedDb -dbPath ."
  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - dynamodb-local
    environment:
      AWS_DEFAULT_PROFILE: local
      AWS_ENDPOINT: --endpoint-url=http://dynamodb-local:8000
    entrypoint: /bin/sh -c
    volumes:
      - './init-scripts:/init-scripts'
    command: >
      '
       for script_name in /init-scripts/*.sh; do
         sh $$script_name
       done
      '
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
    depends_on:
      - dynamodb-local